spring:
  servlet:
    multipart:
      max-file-size=2MB
      max-request-size=2MB
  main:
    banner-mode: "off"
  jpa:
    database: h2
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create-drop

logging:
  level:
    org:
      springframework: ERROR

